project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!analises/"
    - "!analisesR8/"
    - "!analisesv4/"
  
website:
  title: "Aptidão Guaraná"
  navbar:
    background: primary
    search: true
  sidebar:
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



